### ISSUE TITLE
square root of a negative number

### ISSUE THREAD

**Issue by mauriciopoppe** [jonschlinkert/nth-root#1]
`nthRoot(-16)` should be 4i not -4

**Comment by jonschlinkert** [comment]
I had considered that, I just decided to implement it this way because it calculates positive reals correctly and that's what I needed for the code I was writing at the time (fwiw it was for bash expansions in javascript).  But you bring up a good point, this should probably be documented. 

out of curiosity, do you know of any use cases for imaginary units? I'm sure there are plenty I just don't program with complex math very often.

**Comment by mauriciopoppe** [comment]
There are a lot of uses for complex math, I know that 2d complex math is used for example to perform rotations on 2d vectors, my [problem](https://github.com/maurizzzio/function-plot/issues/48) (which is finding the nth-root of a number) also requires checking if it's possible to get the nth root of a number to plot it

Indeed, this should probably be documented

**Comment by jonschlinkert** [comment]
> There are a lot of uses for complex math

well of course! lol I asked about imaginary units specifically, not complex math in general. 

> (which is finding the nth-root of a number) also requires checking if it's possible to get the nth root of a number to plot it

Does the check require the number to also be a positive real number?

**Comment by mauriciopoppe** [comment]
Nope, it can be a negative number as well e.g. `(-8)^(1/3) = -2` but `(-16)^(1/2)=4i`. I've realized that a trivial algorithm won't solve my problem, thanks for taking the time to chat!

**Comment by jonschlinkert** [comment]
no problem, thanks for creating the issue!
